import test from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {createPortraits,normalizePortrait} from './portraits.mjs';
const owner={id:'00000000-0000-0000-0000-000000000001'};
const env={PORTRAIT_OPENROUTER_API_KEY:'test-only',PORTRAIT_MODEL:'test',PORTRAIT_BUDGET_CONFIRMED:'true'};
const image=async()=> (await sharp({create:{width:128,height:128,channels:3,background:'#abcdff'}}).png().toBuffer()).toString('base64');
function db(spent=0,daily=0){const calls=[];const query=async(sql,args)=>{calls.push({sql,args});if(sql.startsWith('SELECT COALESCE'))return {rows:[{spent,daily}]};if(sql.startsWith('SELECT image'))return {rows:[]};return {rowCount:0,rows:[]};};return {calls,query,connect:async()=>({query,release(){}})};}
test('portrait decoder rejects wrong type, oversized and malformed input',async()=>{for(const x of [null,'https://evil.example/image','abc',Buffer.from('<svg/>').toString('base64'),'A'.repeat(8500000)])await assert.rejects(normalizePortrait(x));const output=await normalizePortrait(await image());const m=await sharp(output).metadata();assert.equal(m.width,768);assert.equal(m.format,'jpeg');assert.equal(m.exif,undefined);});
test('generation fails closed until budget is configured and consent is explicit',async()=>{const store=db();const service=createPortraits({db:store,env:{}});assert.equal((await service.handle(owner,'POST',{consent:true})).status,503);const ready=createPortraits({db:store,env});assert.equal((await ready.handle(owner,'POST',{})).status,400);assert.equal(store.calls.length,0);});
test('monthly and daily caps stop calls before contacting provider',async()=>{for(const [spent,daily]of [[500,0],[0,3]]){let contacted=false;const service=createPortraits({db:db(spent,daily),env,fetcher:async()=>{contacted=true;}});assert.equal((await service.handle(owner,'POST',{consent:true,image:await image()})).status,429);assert.equal(contacted,false);}});
test('preview is stored separately; originals never reach database; equip checks owner and candidate',async()=>{const store=db();let request;const original=await image();const service=createPortraits({db:store,env,fetcher:async(url,options)=>{if(url.endsWith('/key'))return {ok:true,json:async()=>({data:{limit:5,limit_reset:'monthly',limit_remaining:5}})};request=JSON.parse(options.body);return {ok:true,json:async()=>({data:[{b64_json:original}]})};}});const result=await service.handle(owner,'POST',{consent:true,image:original});assert.equal(result.status,200);assert.ok(result.body.candidateId);assert.equal(request.n,1);assert.ok(request.input_references[0].image_url.url.startsWith('data:image/jpeg;base64,'));assert.ok(store.calls.some(x=>x.sql.startsWith('INSERT INTO odyssey_portraits(owner,candidate')));assert.equal(store.calls.some(x=>x.args?.includes(original)),false);assert.equal((await service.handle(owner,'PUT',{candidateId:result.body.candidateId})).status,409);const update=store.calls.find(x=>x.sql.startsWith('UPDATE odyssey_portraits'));assert.equal(update.args[0],owner.id);});
test('upstream failure retains spending reservation and leaves current portrait unchanged',async()=>{const store=db();const service=createPortraits({db:store,env,fetcher:async()=>{throw Error('timeout');}});assert.equal((await service.handle(owner,'POST',{consent:true,image:await image()})).status,502);assert.ok(store.calls.some(x=>x.sql.startsWith('INSERT INTO odyssey_portrait_attempts')));assert.equal(store.calls.some(x=>x.sql.startsWith('UPDATE odyssey_portraits')),false);});

test('unlimited provider keys cannot generate even when activation flag is set',async()=>{let paid=false;const service=createPortraits({db:db(),env,fetcher:async(url)=>{if(url.endsWith('/images'))paid=true;return {ok:true,json:async()=>({data:{limit:null,limit_reset:null,limit_remaining:null}})};}});assert.equal((await service.handle(owner,'POST',{consent:true,image:await image()})).status,503);assert.equal(paid,false);});
